#!/usr/bin/env python3

# Import required Python code.
import roslib
NODE_NAME = 'intake_node'
roslib.load_manifest(NODE_NAME)
import rospy
import tf2_ros
import intake_node.main as main
if __name__ == '__main__':
    main.ros_main(NODE_NAME)